In [1]:
from cellcalc import get_primitive_hkl
from interface_generator import core, print_near_axis, \
convert_vector_index, write_trans_file, write_LAMMPS, RBT_deletion_one_by_one
from numpy import array, dot, round, var, average, ceil
from numpy.linalg import inv, norm, det

In [2]:
my_interface = core('Si_mp-149_conventional_standard.cif','Si_mp-149_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


In [3]:
factor = 5.43356/5.468728

In [4]:
my_interface.conv_lattice_1 = my_interface.conv_lattice_1 * factor
my_interface.conv_lattice_2 = my_interface.conv_lattice_2 * factor

In [5]:
my_interface.lattice_1 = my_interface.lattice_1 * factor

In [6]:
my_interface.lattice_2 = my_interface.lattice_2 * factor

In [7]:
axis = convert_vector_index(my_interface.conv_lattice_1, my_interface.lattice_1, [1,0,0])
axis

array([-1., -1.,  1.])

In [8]:
my_interface.parse_limit(du = 1e-4, S  = 1e-4, sgm1=100, sgm2=100, dd = 1e-4)
#Do searching!
#We already know that there is a CSL by rotation 180 degrees
my_interface.search_one_position(axis,36.0,1,0.01)

[5.4335600e+00 0.0000000e+00 4.4408921e-16]
Congrates, we found an appx CSL!

U1 = 
[[ 1  0  1]
 [ 1  1 -2]
 [-1  1  1]]; sigma_1 = 5

U2 = 
[[ 1  1  1]
 [ 1  0 -2]
 [-1  1  0]]; sigma_2 = 5

D = 
[[ 1.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  1.00e+00  1.79e-06]
 [ 0.00e+00 -1.79e-06  1.00e+00]]

axis = [5.4335600e+00 0.0000000e+00 4.4408921e-16] ; theta = 36.87



In [9]:
hkl = get_primitive_hkl(array([0,1,2]), my_interface.conv_lattice_1, my_interface.lattice_1)
hkl

array([-1, -2, -3])

In [10]:
os.chdir(os.path.pardir)

NameError: name 'os' is not defined

In [60]:
my_interface.compute_bicrystal(hkl, orthogonal = True, lim = 50, tol = 1e-2)
my_interface.get_bicrystal(xyz_1 = [9,1,1], xyz_2 = [9,1,1],dp1 = 0.608, dp2 = 0,\
                           filetype = 'LAMMPS', filename = 'atominfile', vx = 10)

cell 1:
[[-1  1 -1]
 [ 1  1  2]
 [ 3 -1 -1]]
cell 2:
[[-1  1 -1]
 [ 1  1  2]
 [ 3 -1 -1]]


In [35]:
my_interface.get_bicrystal(xyz_1 = [9,1,1], xyz_2 = [9,1,1],dp1 = 0, dp2 = 0.5073,\
                            vx = 10)

In [59]:
my_interface.dp_list_1

[0.6074856784138234]

In [12]:
"""
my_interface.define_lammps_regions(['right'],[16.4],[32.15])
v1, v2 = 2*dot(my_interface.orient, my_interface.CNID).T
write_trans_file(v1,v2,50,ceil(norm(v2)/norm(v1))*50)
"""

"\nmy_interface.define_lammps_regions(['right'],[16.4],[32.15])\nv1, v2 = 2*dot(my_interface.orient, my_interface.CNID).T\nwrite_trans_file(v1,v2,50,ceil(norm(v2)/norm(v1))*50)\n"

In [13]:
"""
from numpy import *
dx, dy, dz, energy = loadtxt('results', unpack = True)
import matplotlib.pyplot as plt
plt.figure(figsize = ((max(dy) - min(dy)),(max(dz) - min(dz))))
pcm = plt.scatter(dy,dz, c = energy,cmap = 'hot',s=30,vmin = -300, vmax = 0)
plt.colorbar(pcm,cmap = 'hot')

#since dx is almost zero (interface is in the y-z plane), we just check dz & dy
plt.ylabel('dz (angstrom)',fontsize = 20)
plt.xlabel('dy (angstrom)',fontsize = 20)
plt.axis('scaled')
plt.title('A_A termination',fontsize = 20)
plt.savefig('A_A',dpi = 600)
"""

"\nfrom numpy import *\ndx, dy, dz, energy = loadtxt('results', unpack = True)\nimport matplotlib.pyplot as plt\nplt.figure(figsize = ((max(dy) - min(dy)),(max(dz) - min(dz))))\npcm = plt.scatter(dy,dz, c = energy,cmap = 'hot',s=30,vmin = -300, vmax = 0)\nplt.colorbar(pcm,cmap = 'hot')\n\n#since dx is almost zero (interface is in the y-z plane), we just check dz & dy\nplt.ylabel('dz (angstrom)',fontsize = 20)\nplt.xlabel('dy (angstrom)',fontsize = 20)\nplt.axis('scaled')\nplt.title('A_A termination',fontsize = 20)\nplt.savefig('A_A',dpi = 600)\n"

In [21]:
norm(dot(my_interface.orient, my_interface.CNID)[:,0])/0.2

27.1678

In [61]:
CNID = dot(my_interface.orient, my_interface.CNID)
CNID = dot(inv(my_interface.lattice_bi), CNID)
CNID

array([[-9.09315636e-35,  1.12186184e-18],
       [ 1.00000000e+00, -1.00000000e+00],
       [ 1.05980775e-49,  1.00000000e+00]])

In [48]:
import os
os.getcwd()

'/Users/jasonxie/Desktop/projects/DSC_cm/interface_master_1.1/test_files/sigma5_st_BB'

In [58]:
#os.mkdir('sigma5_st_AB')
os.chdir('sigma5_st_AA')

In [47]:
d_nearest = 2.35820

In [62]:
size_list = [[1, 2], [1, 3], [1, 5], [1, 7], [1, 8],\
             [2, 2], [2, 3], [2, 5], [2, 7], [2, 8],\
             [3, 2], [3, 3], [3, 5], [3, 7], [3, 8],\
             [4, 7], [5, 5], [7, 7]]

for i in size_list:
    name = '{0}{1}'.format(i[0],i[1])
    os.mkdir(name)
    os.chdir(name)
    my_interface.get_bicrystal(xyz_1 = [9,i[0],i[1]], xyz_2 = [9,i[0],i[1]],dp1 = 0, dp2 = 0,\
                           filetype = 'LAMMPS', filename = 'atominfile', vx = 10)
    RBT_deletion_one_by_one(my_interface.lattice_bi, my_interface.atoms_bi, my_interface.elements_bi, CNID, \
                       [28,34], 109, d_nearest, xlo = 106, xhi = 111.5)
    os.chdir(os.path.pardir)

In [57]:
os.chdir(os.path.pardir)

In [63]:
file_epl = open('expansion_loop','w')
file_cl = open('cnid_loop','w')
file_dl = open('deleting_loop','w')


for i in size_list:
    expansion_name = '{0}{1}'.format(i[0],i[1])
    os.chdir(expansion_name)
    for j in range(28):
        for k in range(34):
            cnid_name = '{0} {1}'.format(j,k)
            cnid_name_t = '{0}_{1}'.format(j,k)
            os.rename(cnid_name, cnid_name_t)
            os.chdir(cnid_name_t)
            for h in os.listdir():
                file_epl.write('{0}{1}\n'.format(i[0],i[1]))
                file_dl.write('{}\n'.format(h)) 
                file_cl.write('{} \n'.format(cnid_name_t))
            os.chdir(os.path.pardir)
    os.chdir(os.path.pardir)
file_epl.close()
file_cl.close()
file_dl.close()

In [ ]:
os.rename()

In [65]:
my_interface.define_lammps_regions(['middle','bulk'],[69,39],[149,69])

In [64]:
os.getcwd()

'/Users/jasonxie/Desktop/projects/DSC_cm/interface_master_1.1/test_files/sigma5_st_AA'

In [89]:
norm(my_interface.lattice_bi[:,0])

85.20271999999999