In [25]:
from cellcalc import get_primitive_hkl
from interface_generator import core, print_near_axis, convert_vector_index
from numpy import array
from numpy import array, dot, round
from numpy.linalg import inv

# Define an interface core class

# Input two cif files.

For GBs, input the same file; for interfaces, input two different files.


The first structure is non-changed while the second one can be deformed to form an approximate CSL

Please input files of CONVENTIONAL cells if you are not familiar with the indices in the primitive cell.

In [2]:
my_interface = core('Si_mp-149_conventional_standard.cif', 'SiC_mp-568656_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


Find two vectors from different crystals with close length

In [3]:
print_near_axis(0.1, my_interface.lattice_1, my_interface.lattice_2)

       e1        e2       dv      length_v1    length_v2
[ 4. -2. -2.] [ 2. -3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4.  0. -2.] [-2.  3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4.  0. -2.] [-2. -5. -0.] 0.09369474498382502 13.395593142071164 13.489287887054989
[ 4.  0. -2.] [-3.  2. -0.] 0.09369474498382857 13.395593142071164 13.489287887054992
[ 4.  0. -2.] [-3. -5. -0.] 0.0936947449838268 13.395593142071164 13.48928788705499
[ 4.  0. -2.] [-5. -2. -0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4.  0. -2.] [-5. -3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4. -2. -2.] [ 3. -2.  0.] 0.09369474498382857 13.395593142071164 13.489287887054992
[ 4. -2. -2.] [-2.  3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4. -2. -2.] [-2. -5. -0.] 0.09369474498382502 13.395593142071164 13.489287887054989
[ 4.  0. -2.] [ 2. -3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994

[ 1. -5.  1.] [-4.  2. -0.] 0.03080958789513133 16.406184 16.37537441210487
[-3.  3. -3.] [-2.  4. -0.] 0.030809587895134882 16.406184 16.375374412104865
[ 1. -5.  1.] [ 2. -4.  0.] 0.030809587895134882 16.406184 16.375374412104865
[ 1. -5.  1.] [ 4. -2.  0.] 0.03080958789513133 16.406184 16.37537441210487
[1. 3. 1.] [-4.  2. -0.] 0.03080958789513133 16.406184 16.37537441210487
[1. 3. 1.] [-2.  4. -0.] 0.030809587895134882 16.406184 16.375374412104865
[1. 3. 1.] [ 2. -4.  0.] 0.030809587895134882 16.406184 16.375374412104865
[ 3. -5.  1.] [-4.  2. -0.] 0.03080958789513133 16.406184 16.37537441210487
[1. 3. 1.] [ 4. -2.  0.] 0.03080958789513133 16.406184 16.37537441210487
[ 3. -3.  3.] [-2.  4. -0.] 0.030809587895134882 16.406184 16.375374412104865
[ 3. -3.  3.] [ 2. -4.  0.] 0.030809587895134882 16.406184 16.375374412104865
[ 3. -3.  3.] [ 4. -2.  0.] 0.03080958789513133 16.406184 16.37537441210487
[ 3. -5.  1.] [-2.  4. -0.] 0.030809587895134882 16.406184 16.375374412104865
[ 3. -5.  

[-3. -4. -1.] [-1.  1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [ 1. -1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [ 1.  2. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [ 2.  1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [-2. -1.  1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[3. 1. 4.] [-1.  1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [-1.  1.  1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [ 1. -1.  1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [2. 1. 1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-4. -3. -1.] [-1. -2.  1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[1. 3. 4.] [-2. -1.  1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-1. -4. -3.] [1. 2. 1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[1. 

[ 2. -5. -4.] [3. 1. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-3. -2.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -4. -5.] [-3. -2. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [-3. -1. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [2. 3. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [ 2. -1.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [1. 3. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [ 1. -2.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [-1.  2.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [-1. -3.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [-2.  1.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5. -1. -2.] [-2. -3.  1.] 0.08989811107630175 26.510642571288

[-4. -5.  1.] [4. 0. 1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[-5. -4.  1.] [-4. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[ 1. -4. -5.] [ 4.  4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [-4.  0.  1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[ 1. -4. -5.] [-4. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[ 1. -4. -5.] [-4.  0. -1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[ 1. -4. -5.] [ 0. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [ 0. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [-4.  0. -1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[-4.  1. -5.] [4. 4. 1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [4. 0. 1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[-4.  1. -5.] [0. 4. 1.] 0.02211472710369833 28.152000414829775

[-5. -5.  2.] [-5.  0.  1.] 0.03846104186806798 29.702795915040184 29.664334873172116
[-5. -5.  2.] [ 0. -5.  1.] 0.03846104186806798 29.702795915040184 29.664334873172116
[-0. -5. -4.] [-4.  2. -1.] 0.05732937414101613 30.202037532400222 30.144708158259206
[-0. -4. -5.] [-4.  2. -1.] 0.05732937414101613 30.202037532400222 30.144708158259206
[-0. -4. -5.] [-2.  4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -5. -4.] [ 2. -4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -5. -4.] [ 4. -2. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -5. -4.] [-2.  4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -4. -5.] [ 2. -4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -4. -5.] [ 4. -2.  1.] 0.05732937414101613 30.202037532400222 30.144708158259206
[-0. -4. -5.] [-4.  2.  1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -4. -5.] [-2.  4.  1.] 0.057329374141019684

In [4]:
axis = convert_vector_index(my_interface.conv_lattice_1, my_interface.lattice_1, [1,-1,1])
axis

array([ 1., -3.,  1.])

We select [ 4 -2 -2 ] of lattice 1, [ 2 -3 0 ] of lattice 2.

Adjust the orientation of lattice 2 to make these two vectors colinnear 

In [5]:
my_interface.set_orientation_axis([4, -2, -2], [2, -3, 0])

Searching for an approximate CSL by rotating crystal 2 along the [4, -2, -2] axis of
crystal 1

In [7]:
my_interface.parse_limit(du = 0.2, S  = 0.2, sgm1=100, sgm2=100, dd = 0.2)
#Do searching... this might take a long time...
axis = [4, -2, -2]
my_interface.search_one_position(axis,0,180,0.5)

Congrates, we found an appx CSL!

U1 = 
[[ 0 -2  6]
 [ 0  3  3]
 [-3 -2 -6]]; sigma_1 = 72

U2 = 
[[ 2  4  1]
 [-2  2 -1]
 [ 0  0  1]]; sigma_2 = 72

D = 
[[ 1.07137686 -0.07279757  0.00292049]
 [ 0.01567533  1.03202845 -0.03105994]
 [-0.03754006 -0.0411393   1.05714645]]

axis = [-5.468728 -5.468728 10.937456] ; theta = 6.0



# Determining the interface plane to be a CSL lattice plane

In [8]:
hkl = get_primitive_hkl(array([0,0,1]), my_interface.CSL, my_interface.lattice_1)
hkl

array([3, 2, 0])

# Make a bicrystal!
Please refer to another tutorial to get the meaning of the relative parameters 

In [23]:
my_interface.compute_bicrystal(hkl, orthogonal = False)
my_interface.get_bicrystal(xyz = [1,1,1],dp2 = 2.5, vx = 5)

cell 1:
[[-6  0  2]
 [-3  0 -3]
 [ 6 -3  2]]
cell 2:
[[-6  0  2]
 [-3  0 -3]
 [ 6 -3  2]]


In [26]:
CNID_conv = round(dot(inv(my_interface.conv_lattice_1)\
                              , my_interface.CNID),8)
CNID_conv

array([[-0.        , -0.08333333],
       [-0.25      ,  0.08333333],
       [-0.25      , -0.33333333]])

Check the generated POSCAR file