# TiO2 surface slab

## import & prepare

In [1]:
!pip install git+https://github.com/nmdl-mizo/interface_master.git@develop
!mkdir -p cif_files
!curl https://raw.githubusercontent.com/nmdl-mizo/interface_master/develop/test_files/cif_files/TiO2_mp-2657_conventional_standard.cif -o 'cif_files/TiO2_mp-2657_conventional_standard.cif'

Defaulting to user installation because normal site-packages is not writeable
  Cloning https://github.com/nmdl-mizo/interface_master.git (to revision develop) to /tmp/pip-req-build-uugit09c
  Running command git clone --filter=blob:none --quiet https://github.com/nmdl-mizo/interface_master.git /tmp/pip-req-build-uugit09c
  Resolved https://github.com/nmdl-mizo/interface_master.git to commit 2bdf96ed4835b036557ac18de82b4fa2afdabf24
  Preparing metadata (setup.py) ... done

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   955  100   955    0     0      0      0 --:--:-- --:--:-- --:--:--     0     0   2713      0 --:--:-- --:--:-- --:--:--  2705


In [2]:
from interfacemaster.interface_generator import get_surface_slab, terminates_scanner_slab_structure
from interfacemaster.cellcalc import get_primitive_hkl
from pymatgen.core.structure import Structure
from numpy import ceil

## Load structures

In [3]:
primitive_unit_structure =  Structure.from_file('cif_files/TiO2_mp-2657_conventional_standard.cif', \
                                     primitive=True, sort=False, merge_tol=0.0)

In [4]:
conv_unit_structure = Structure.from_file('cif_files/TiO2_mp-2657_conventional_standard.cif', \
                                     primitive=False, sort=False, merge_tol=0.0)

In [5]:
#get all the non-identical terminations
hkl_in_pri = get_primitive_hkl(hkl=[1,0,1], C_lattice=conv_unit_structure.lattice.matrix.T, \
                              P_lattice=primitive_unit_structure.lattice.matrix.T)
plane_list, element_list, dp_list = terminates_scanner_slab_structure(primitive_unit_structure, hkl_in_pri)

cross vector: 
[[1]
 [0]
 [0]]
length: 2.969203
plane basis: 
[[ 0  1]
 [ 0 -1]
 [ 1  0]]
length: 4.653272 5.519882857560747


In [6]:
#height
dp_list

[0.7623739121169246, 1.7406639121169247, 2.5030439121169246]

## The function below generates a slab with its bc-plane is a specified (hkl) lattice plane
### Customerization options:  
**replica** --- expand from primitive slab cell, **default: [1,1,1]**  
**inclination_tol** --- required minimum cos value of the angle between the basic crossing vector and the surface, **default: gamma angle > 45 degrees**  
**termi_shift** --- shift the termination of the surface, **default: 0**  
**vacuum_height** --- height of vaccum, **default:  0**  
**plane_normal** --- whether requiring the two vectors in the surface plane to be perpendicular, **default: False**  
**normal_perp** --- whether requiring the crossing vector to be perpendicular to the plane, **default:  False**  
**normal_tol** --- tolerance to judge whether normal/perpendicular, **default: 1e-3**  
**lim** --- control the number of generated vectors to search for the crossing vectors and perpendicular vectors, **default: 20**    
**filename** --- name of the generated atom files, **default:  'POSCAR'**  
**filetype** --- type of the generated atom files (for VASP or LAMMPS), **default: 'VASP'**

In [16]:
#get orthogonal cell
slab_structure = get_surface_slab(conv_unit_structure, hkl = [1,0,1], vacuum_height = 15, \
                                  plane_normal = True, normal_perp = True, termi_shift = 1.75)

cross vector: 
[[2]
 [0]
 [5]]
length: 17.521869837553325
plane basis: 
[[ 0  1]
 [-1  0]
 [ 0 -1]]
length: 4.653272 5.519882857560747


In [5]:
#expansion to reach a required slab size with length_a > 5, length_b > 10, length_c > 10
da, db, dc = ceil(5/6.580720371810977), ceil(10/2.969203), ceil(10/6.580720371810977)
slab_structure = get_surface_slab(unit_structure, hkl = [1,1,0], replica = [da, db, dc], vacuum_height = 20)

cross vector: 
[[-1]
 [-1]
 [ 0]]
length: 6.580720371810977
plane basis: 
[[ 0 -1]
 [ 0  1]
 [ 1  0]]
length: 2.969203 6.580720371810977


**Try other customerization options :D**