In [1]:
from interfacemaster.cellcalc import get_primitive_hkl
from interfacemaster.interface_generator import core, print_near_axis, convert_vector_index
from numpy import array
from numpy import array, dot, round
from numpy.linalg import inv

# Define an interface core class

# Input two cif files.

For GBs, input the same file; for interfaces, input two different files.


The first structure is non-changed while the second one can be deformed to form an approximate CSL

Please input files of CONVENTIONAL cells if you are not familiar with the indices in the primitive cell.

In [2]:
my_interface = core('cif_files/Si_mp-149_conventional_standard.cif', \
                    'cif_files/SiC_mp-568656_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


Find two vectors from different crystals with close length

In [3]:
print_near_axis(0.1, my_interface.lattice_1, my_interface.lattice_2)

       e1        e2       dv      length_v1    length_v2
[ 4. -2. -2.] [ 2. -3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4.  0. -2.] [-2.  3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4.  0. -2.] [-2. -5. -0.] 0.09369474498382502 13.395593142071164 13.489287887054989
[ 4.  0. -2.] [-3.  2. -0.] 0.09369474498382857 13.395593142071164 13.489287887054992
[ 4.  0. -2.] [-3. -5. -0.] 0.0936947449838268 13.395593142071164 13.48928788705499
[ 4.  0. -2.] [-5. -2. -0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4.  0. -2.] [-5. -3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4. -2. -2.] [ 3. -2.  0.] 0.09369474498382857 13.395593142071164 13.489287887054992
[ 4. -2. -2.] [-2.  3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994
[ 4. -2. -2.] [-2. -5. -0.] 0.09369474498382502 13.395593142071164 13.489287887054989
[ 4.  0. -2.] [ 2. -3.  0.] 0.09369474498383035 13.395593142071164 13.489287887054994

[ 4.  0. -4.] [-5.  0.  0.] 0.005375786941023364 15.467898613058981 15.473274400000005
[ 4.  0. -4.] [ 0. -5.  0.] 0.005375786941019811 15.467898613058981 15.473274400000001
[ 0.  0. -4.] [-5. -5.  0.] 0.005375786941019811 15.467898613058981 15.473274400000001
[ 0.  0. -4.] [-5.  0.  0.] 0.005375786941023364 15.467898613058981 15.473274400000005
[ 0.  0. -4.] [ 0. -5.  0.] 0.005375786941019811 15.467898613058981 15.473274400000001
[ 0. -4.  4.] [-5.  0.  0.] 0.005375786941023364 15.467898613058981 15.473274400000005
[-4.  0.  0.] [-5. -5.  0.] 0.005375786941019811 15.467898613058981 15.473274400000001
[ 0.  4. -4.] [-5.  0.  0.] 0.005375786941023364 15.467898613058981 15.473274400000005
[ 4. -4.  0.] [-5. -5.  0.] 0.005375786941019811 15.467898613058981 15.473274400000001
[ 4. -4.  0.] [-5.  0.  0.] 0.005375786941023364 15.467898613058981 15.473274400000005
[ 4. -4.  0.] [ 0. -5.  0.] 0.005375786941019811 15.467898613058981 15.473274400000001
[ 0. -4.  4.] [-5. -5.  0.] 0.0053757869410

[3. 1. 2.] [ 2. -5.  0.] 0.008759734989890688 19.33487326632373 19.32611353133384
[1. 2. 3.] [ 2. -5.  0.] 0.008759734989890688 19.33487326632373 19.32611353133384
[3. 1. 2.] [-5.  2.  0.] 0.008759734989887136 19.33487326632373 19.326113531333842
[1. 3. 2.] [ 2. -5.  0.] 0.008759734989890688 19.33487326632373 19.32611353133384
[1. 3. 2.] [-5.  2.  0.] 0.008759734989887136 19.33487326632373 19.326113531333842
[1. 2. 3.] [-5.  2.  0.] 0.008759734989887136 19.33487326632373 19.326113531333842
[2. 1. 3.] [-5.  2.  0.] 0.008759734989887136 19.33487326632373 19.326113531333842
[2. 1. 3.] [ 2. -5.  0.] 0.008759734989890688 19.33487326632373 19.32611353133384
[3. 2. 1.] [-5.  2.  0.] 0.008759734989887136 19.33487326632373 19.326113531333842
[-2. -3. -1.] [-5.  2.  0.] 0.008759734989887136 19.33487326632373 19.326113531333842
[-2. -3. -1.] [ 2. -5.  0.] 0.008759734989890688 19.33487326632373 19.32611353133384
[-3. -2. -1.] [ 2. -5.  0.] 0.008759734989890688 19.33487326632373 19.32611353133384
[

[-4. -3. -1.] [ 1. -1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-4. -3. -1.] [-1.  1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-4. -3. -1.] [-1. -2. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-4. -3. -1.] [-2. -1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [-2. -1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[1. 3. 4.] [-2. -1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[1. 3. 4.] [-1. -2. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[1. 3. 4.] [-1.  1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [-1. -2. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [-1.  1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [ 1. -1. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[-3. -4. -1.] [ 1.  2. -1.] 0.06998474466934113 25.94045457590595 25.87046983123661
[

[-4.  2. -5.] [-2.  1.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [-1. -3.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [-1.  2.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [ 1. -2.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [1. 3. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [ 2. -1.  1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [2. 3. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [3. 1. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-4.  2. -5.] [3. 2. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-2. -1. -5.] [-3. -2. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-2. -1. -5.] [-3. -1. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-2. -1. -5.] [-2. -3. -1.] 0.08989811107630175 26.510642571288685

[ 2. -5. -4.] [ 2. -1. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [ 1.  3. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [ 1. -2. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-1.  2. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-1. -3. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-2.  1. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-2. -3. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-3. -1. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -5. -4.] [-3. -2. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[-5.  2. -4.] [1. 3. 1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -4. -5.] [ 3.  2. -1.] 0.08989811107630175 26.510642571288685 26.600540682364986
[ 2. -4. -5.] [-3. -1.  1.] 0.08989811107630175 26.510642

[ 4. -5. -5.] [4. 3. 1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[-5. -5.  4.] [ 1.  4. -1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[ 4. -5. -5.] [-4. -3. -1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[ 4. -5. -5.] [-4. -1. -1.] 0.043816276180358216 27.615722721279482 27.65953899745984
[ 4. -5. -5.] [-3. -4. -1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[ 4. -5. -5.] [-3.  1. -1.] 0.043816276180358216 27.615722721279482 27.65953899745984
[ 4. -5. -5.] [-1. -4. -1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[ 4. -5. -5.] [-1.  3. -1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[-5. -5.  4.] [4. 1. 1.] 0.043816276180358216 27.615722721279482 27.65953899745984
[ 4. -5. -5.] [ 1. -3. -1.] 0.04381627618035466 27.615722721279482 27.659538997459837
[ 4. -5. -5.] [ 3. -1. -1.] 0.043816276180358216 27.615722721279482 27.65953899745984
[ 4. -5. -5.] [ 3.  4. -1.] 0.04381627618035466 27.615722721

[ 1. -5. -4.] [ 0. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [-4. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[ 1. -5. -4.] [-4.  0. -1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[ 1. -5. -4.] [-4. -4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[ 1. -4. -5.] [ 0.  4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [ 0. -4.  1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [-4. -4.  1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[-4.  1. -5.] [ 4.  4. -1.] 0.02211472710369833 28.152000414829775 28.174115141933473
[ 1. -5. -4.] [-4.  0.  1.] 0.02211472710370188 28.152000414829775 28.174115141933477
[2. 3. 4.] [-3.  2.  1.] 0.0012085073356331577 28.67825157317928 28.679460080514914
[3. 2. 4.] [ 2. -3.  1.] 0.0012085073356367104 28.67825157317928 28.679460080514918
[3. 2. 4.] [ 3. -2.  1.] 0.0012085073356331577 28.67825157

[2. 3. 4.] [-3. -5. -1.] 0.0012085073356331577 28.67825157317928 28.679460080514914
[-2. -3. -4.] [ 3. -2.  1.] 0.0012085073356331577 28.67825157317928 28.679460080514914
[-2. -3. -4.] [ 2. -3.  1.] 0.0012085073356367104 28.67825157317928 28.679460080514918
[-2. -3. -4.] [-2.  3.  1.] 0.0012085073356367104 28.67825157317928 28.679460080514918
[-2. -3. -4.] [-2. -5.  1.] 0.001208507335629605 28.67825157317928 28.67946008051491
[-2. -3. -4.] [-3.  2.  1.] 0.0012085073356331577 28.67825157317928 28.679460080514914
[3. 2. 4.] [-3.  2. -1.] 0.0012085073356331577 28.67825157317928 28.679460080514914
[3. 2. 4.] [-2. -5. -1.] 0.001208507335629605 28.67825157317928 28.67946008051491
[3. 2. 4.] [-2.  3. -1.] 0.0012085073356367104 28.67825157317928 28.679460080514918
[3. 2. 4.] [ 2. -3. -1.] 0.0012085073356367104 28.67825157317928 28.679460080514918
[3. 4. 2.] [-2.  3.  1.] 0.0012085073356367104 28.67825157317928 28.679460080514918
[3. 2. 4.] [ 3. -2. -1.] 0.0012085073356331577 28.67825157317928 

[-5. -5.  2.] [-5. -5.  1.] 0.03846104186806798 29.702795915040184 29.664334873172116
[-5. -5.  2.] [-5.  0.  1.] 0.03846104186806798 29.702795915040184 29.664334873172116
[-5. -5.  2.] [ 0. -5.  1.] 0.03846104186806798 29.702795915040184 29.664334873172116
[-0. -5. -4.] [-4.  2. -1.] 0.05732937414101613 30.202037532400222 30.144708158259206
[-0. -4. -5.] [-4.  2. -1.] 0.05732937414101613 30.202037532400222 30.144708158259206
[-0. -4. -5.] [-2.  4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -5. -4.] [ 2. -4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -5. -4.] [ 4. -2. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -5. -4.] [-2.  4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -4. -5.] [ 2. -4. -1.] 0.057329374141019684 30.202037532400222 30.144708158259203
[-0. -4. -5.] [ 4. -2.  1.] 0.05732937414101613 30.202037532400222 30.144708158259206
[-0. -4. -5.] [-4.  2.  1.] 0.057329374141019684 

In [4]:
axis = convert_vector_index(my_interface.conv_lattice_1, my_interface.lattice_1, [1,-1,1])
axis

array([ 1., -3.,  1.])

We select [ 4 -2 -2 ] of lattice 1, [ 2 -3 0 ] of lattice 2.

Adjust the orientation of lattice 2 to make these two vectors colinnear 

In [5]:
my_interface.set_orientation_axis([4, -2, -2], [2, -3, 0])

Searching for an approximate CSL by rotating crystal 2 along the [4, -2, -2] axis of
crystal 1

In [6]:
my_interface.parse_limit(du = 0.2, S  = 0.2, sgm1=100, sgm2=100, dd = 0.2)
#Do searching... this might take a long time...
axis = [4, -2, -2]
my_interface.search_one_position(axis,0,180,0.5)

[-5.468728 -5.468728 10.937456]
Congrates, we found an appx CSL!

U1 = 
[[ 3  1  4]
 [-1  2  3]
 [-2 -3  1]]; sigma_1 = 56

U2 = 
[[ 2  4  2]
 [-2  2  0]
 [ 0  0  1]]; sigma_2 = 56

D = 
[[ 0.95167688  0.07166751  0.        ]
 [-0.07166751  0.95167688 -0.        ]
 [ 0.         -0.          0.99801939]]

axis = [-5.468728 -5.468728 10.937456] ; theta = 0.0



# Determining the interface plane to be a CSL lattice plane

In [7]:
hkl = get_primitive_hkl(array([1,0,0]), my_interface.CSL, my_interface.lattice_1)
hkl

array([ 11, -13,  -5])

# Make a bicrystal!
Please refer to another tutorial to get the meaning of the relative parameters 

In [8]:
my_interface.compute_bicrystal(hkl, orthogonal = False)
my_interface.get_bicrystal(xyz_1 = [1,1,1], xyz_2 = [1,1,1], dp2 = 1)

cell 1:
[[ 2  1  4]
 [-3  2  3]
 [ 1 -3  1]]
cell 2:
[[ 2  1  4]
 [-3  2  3]
 [ 1 -3  1]]
[0.00583 0.00586 0.01417 0.01419 0.03918 0.03926 0.04753 0.04754 0.07253
 0.07259 0.08083 0.08085 0.10583 0.10584 0.11419 0.13926 0.14752 0.14754
 0.1725  0.17253 0.18084 0.18086 0.20584 0.20593 0.21419 0.21421 0.2392
 0.23926 0.2475  0.24752 0.2725  0.28086 0.30593 0.31419 0.3142  0.33916
 0.3392  0.34751 0.34753 0.37251 0.37259 0.38086 0.38087 0.40587 0.40592
 0.41417 0.41418 0.43916 0.43917 0.44752 0.47259 0.48085 0.48087 0.50583
 0.50586 0.51417 0.51419 0.53918 0.53926 0.54753 0.54754 0.57253 0.57259
 0.58083 0.58085 0.60583 0.60584 0.61419 0.63926 0.64752 0.64754 0.6725
 0.67253 0.68084 0.68086 0.70584 0.70593 0.71419 0.71421 0.7392  0.73926
 0.7475  0.74752 0.7725  0.78086 0.80593 0.81419 0.8142  0.83916 0.8392
 0.84751 0.84753 0.87251 0.87259 0.88086 0.88087 0.90587 0.90592 0.91417
 0.91418 0.93916 0.93917 0.94752 0.97259 0.98085 0.98087]
0.00595238095238095


In [9]:
CNID_conv = round(dot(inv(my_interface.conv_lattice_1)\
                              , my_interface.CNID),8)
CNID_conv

array([[ 0.75,  2.75],
       [-0.5 ,  3.  ],
       [-0.25,  2.25]])

Check the generated POSCAR file