In [1]:
from interfacemaster.interface_generator import get_surface_slab
from pymatgen.core.structure import Structure
from numpy import ceil

In [2]:
unit_structure = Structure.from_file('cif_files/TiO2_mp-554278_conventional_standard.cif', primitive=False, sort=False, merge_tol=0.0)

In [3]:
#get primitive slab
slab_structure = get_surface_slab(unit_structure, hkl = [1,1,0], inclination_tol=0)

plane basis: 
[[ 0.  1.]
 [ 0. -1.]
 [ 1.  1.]]
length: 6.61621224 12.726574587701176
cross vector: 
[0. 1. 0.]
length: 3.766936


In [6]:
#expansion
dx, dy, dz = ceil(10/3.766936), ceil(10/6.61621224), ceil(10/12.726574587701176)
slab_structure = get_surface_slab(unit_structure, hkl = [1,1,0], inclination_tol=0, replica = [dx, dy, dz],\
                                 vacuum_height = 20, filetype = 'LAMMPS')

plane basis: 
[[ 0.  1.]
 [ 0. -1.]
 [ 1.  1.]]
length: 6.61621224 12.726574587701176
cross vector: 
[0. 1. 0.]
length: 3.766936
