# Graphene - Approximate

In [25]:
import sys
sys.path.append('../interfacemaster/')

In [26]:
from interfacemaster.cellcalc import get_primitive_hkl, get_pri_vec_inplane, get_normal_index, get_normal_from_MI, rot
from interfacemaster.interface_generator import core, print_near_axis, convert_vector_index
from numpy import array, dot, round, cross, eye, pi, ceil
from numpy.linalg import inv, det, norm
from gb_code.csl_generator import print_list

In [27]:
my_interface = core('cif_files/C_mp-990448_conventional_standard.cif',\
                    'cif_files/C_mp-990448_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


In [64]:
#combine the two [001] surfaces (graphene)
hkl_1 = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_1, my_interface.lattice_1)
hkl_2 = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_2, my_interface.lattice_2)

## Searching two_dimensional CSL

In [65]:
#a known target disorientation giving CSL
R = rot(a=[0,0,1],Theta = 46.83/180 * pi)

In [66]:
my_interface.parse_limit(du = 1e-3, S  = 1e-3, sgm1=100, sgm2=100, dd = 1e-3)

#Do searching!
my_interface.search_one_position_2D(hkl_1, hkl_2, theta_range = 1, dtheta=0.01, pre_dt=True, pre_R = R, exact=True)

Congrates, we found an appx CSL!

U1 = 
[[ 3  2]
 [-2  5]
 [ 0  0]]; sigma_1 = 19

U2 = 
[[ 5 -2]
 [ 2  3]
 [ 0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

axis = [ 3.23108364e-16  5.59640103e-16 -5.27676003e+00] ; theta = 0.0



## Get bicrystal

In [67]:
my_interface.compute_bicrystal_two_D(hkl_1 = hkl_1, hkl_2=hkl_2, normal_ortho = False, plane_ortho = False, lim = 50, tol_ortho = 1e-2, tol_integer=1e-3)

cell 1:
[[ 0  3  2]
 [ 0 -2  5]
 [ 1  0  0]]
cell 2:
[[ 0  5 -2]
 [ 0  2  3]
 [ 1  0  0]]


In [68]:
my_interface.get_bicrystal(two_D = True, xyz_1 = [1,1,1], xyz_2 = [1,1,1], dp1 = 9.99905800e+00-3.4, filetype= 'VASP')

In [69]:
n1 = int(ceil(norm(my_interface.CNID[:,0])/0.5))
n2 = int(ceil(norm(my_interface.CNID[:,1])/0.5))

In [70]:
my_interface.sample_CNID([n1,n2], dp1 = 9.99905800e+00-3.4)

CNID
[[ 0.28571429  0.42857143]
 [-0.14285714  0.28571429]
 [ 0.          0.        ]]
making 4 files...
completed


Please check the POSCAR file