# Co

## import & prepare

In [1]:
!pip install git+https://github.com/nmdl-mizo/interface_master.git@develop
!mkdir -p cif_files
!curl https://raw.githubusercontent.com/nmdl-mizo/interface_master/develop/test_files/cif_files/Co_mp-54_conventional_standard.cif -o 'cif_files/Co_mp-54_conventional_standard.cif'

Defaulting to user installation because normal site-packages is not writeable
  Cloning https://github.com/nmdl-mizo/interface_master.git (to revision develop) to /tmp/pip-req-build-lccafuui
  Running command git clone --filter=blob:none --quiet https://github.com/nmdl-mizo/interface_master.git /tmp/pip-req-build-lccafuui
  Resolved https://github.com/nmdl-mizo/interface_master.git to commit 2bdf96ed4835b036557ac18de82b4fa2afdabf24
  Preparing metadata (setup.py) ... done

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   747  100   747    0     0   2575      0 --:--:-- --:--:-- --:--:--  2575


In [30]:
from interfacemaster.cellcalc import get_primitive_hkl, get_normal_from_MI, MID, rot
from interfacemaster.interface_generator import core, convert_vector_index, get_disorientation
from numpy import array, dot, round, var, average, ceil, pi
from numpy.linalg import inv,norm

## Define an interface core class

Input two cif files.For GBs, input the same file; for interfaces, input two different files.


The first structure is non-changed while the second one can be deformed to form an approximate CSL

Please input files of CONVENTIONAL cells if you are not familiar with the indices in the primitive cell.

In [11]:
my_interface = core('cif_files/Co_mp-54_conventional_standard.cif',\
                    'cif_files/Co_mp-54_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


In [3]:
#my_interface.atoms_2 = [1,1,1] - my_interface.atoms_2

In [1]:
from symmetric_tilt_co_111 import sample_STGB

In [2]:
thetas, sigmas, hkls = sample_STGB([1,1,1], 10, 100, 10)

60.000000003954064
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  1  0]
 [-1  1  0]
 [ 0  0  1]]; sigma_1 = 1

U2 = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]; sigma_2 = 1

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

38.21321070399773
Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


Congrates, we found an appx CSL!

U1 = 
[[ 0  2  1]
 [ 0 -1  3]
 [ 1  0  0]]; sigma_1 = 7

U2 = 
[[ 0  3 -1]
 [ 0  1  2]
 [ 1  0  0]]; sigma_2 = 7

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

46.82644889565461
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  2 -5]
 [ 0  5 -3]
 [ 1  0  0]]; sigma_1 = 19

U2 = 
[[ 0 -2 -3]
 [ 0  3 -5]
 [ 1  0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

50.56999209530953
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  3 -4]
 [ 0  7  3]
 [ 1  0  0]]; sigma_1 = 37

U2 = 
[[ 0 -3 -7]
 [ 0  4 -3]
 [ 1  0  0]]; sigma_2 = 37

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

52.65900698674047
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  4 -9]
 [ 0  9 -5]
 [ 1  0  0]]; sigma_1 = 61

U2 = 
[[ 0 -4 -5]
 [ 0  5 -9]
 [ 1  0  0]]; sigma_2 = 61

D = 
[[1. 0. 0.]
 

Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[  0  -9  23]
 [  0 -23  14]
 [  1   0   0]]; sigma_1 = 403

U2 = 
[[  0   9  14]
 [  0 -14  23]
 [  1   0   0]]; sigma_2 = 403

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

13.173551107883242
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  2  3]
 [ 0 -3  5]
 [ 1  0  0]]; sigma_1 = 19

U2 = 
[[ 0  3  2]
 [ 0 -2  5]
 [ 1  0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

35.56730232261096
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  2  9]
 [ 0 -7  2]
 [ 1  0  0]]; sigma_1 = 67

U2 = 
[[ 0  7  9]
 [ 0 -2  7]
 [ 1  0  0]]; sigma_2 = 67

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

40.34714037075397
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  2  9]
 [ 0 -9 11]
 [ 1  0  0]]; 

Warning!, this programme will rewrite the POSCAR file in this dir!
Warning!, this programme will rewrite the POSCAR file in this dir!


In [7]:
hkls

array([[ 9, -8,  0],
       [ 8, -7,  0],
       [ 7, -6,  0],
       [ 6, -5,  0],
       [ 5, -4,  0],
       [ 9, -7,  0],
       [ 4, -3,  0],
       [ 7, -5,  0],
       [ 3, -2,  0],
       [ 8, -5,  0],
       [ 5, -3,  0],
       [ 7, -4,  0],
       [ 9, -5,  0],
       [ 2, -1,  0]])

In [13]:
my_interface.conv_lattice_1[:,0] +  my_interface.conv_lattice_1[:,1]

array([1.25039190e+00, 2.16574230e+00, 3.06257688e-16])

In [39]:
#get the rotation mtx
import os
os.mkdir('co<001>tst_GBs_POSCAR')

In [35]:
thetas/pi * 180

array([11.63505129, 13.17355111, 15.17817894, 17.89655113, 21.7867893 ,
       24.43269768, 27.7957725 , 32.20422751, 38.2132107 , 43.5735786 ,
       46.8264489 , 50.5699921 , 52.65900699, 60.        ])

In [36]:
small_thetas = thetas[thetas/pi * 180 < 30]

In [41]:
for i in range(len(small_thetas)):
    R = rot([0,0,1], small_thetas[i])
    hkl1 = get_primitive_hkl(C_lattice = my_interface.conv_lattice_1, P_lattice = my_interface.lattice_1, hkl=[0,0,1])
    my_interface.search_fixed(R, exact = True)
    my_interface.compute_bicrystal(hkl1, plane_ortho=True, normal_ortho= True, lim = 50, tol_ortho = 1e-3)
    x_dimension = ceil(70/norm(dot(my_interface.lattice_1,my_interface.bicrystal_U1)[:,0]))
    hkl2 = get_primitive_hkl(C_lattice = my_interface.conv_lattice_1, P_lattice = dot(R, my_interface.conv_lattice_1), hkl = hkls[i])
    my_interface.get_bicrystal(xyz_1 = [x_dimension,1,1], \
                                   xyz_2 = [x_dimension,1,1], \
                               filename = 'co<001>tst_GBs_POSCAR/sigma{0}'.\
                               format(sigmas[i]),filetype='VASP')

Congrates, we found an appx CSL!

U1 = 
[[ 0  8  1]
 [ 0 -1  9]
 [ 1  0  0]]; sigma_1 = 73

U2 = 
[[ 0  9 -1]
 [ 0  1  8]
 [ 1  0  0]]; sigma_2 = 73

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cell 1:
[[ 0 -1 17]
 [ 0 -9  7]
 [ 1  0  0]]
cell 2:
[[ 0  1 17]
 [ 0 -8 10]
 [ 1  0  0]]
Congrates, we found an appx CSL!

U1 = 
[[ 0  2  3]
 [ 0 -3  5]
 [ 1  0  0]]; sigma_1 = 19

U2 = 
[[ 0  3  2]
 [ 0 -2  5]
 [ 1  0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cell 1:
[[ 0 -3 -7]
 [ 0 -5  1]
 [-1  0  0]]
cell 2:
[[ 0 -2 -8]
 [ 0 -5 -1]
 [-1  0  0]]
Congrates, we found an appx CSL!

U1 = 
[[ 0  6  7]
 [ 0 -1  6]
 [ 1  0  0]]; sigma_1 = 43

U2 = 
[[0 7 6]
 [0 1 7]
 [1 0 0]]; sigma_2 = 43

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cell 1:
[[ 0 -1 13]
 [ 0 -7  5]
 [ 1  0  0]]
cell 2:
[[ 0  1 13]
 [ 0 -6  8]
 [ 1  0  0]]
Congrates, we found an appx CSL!

U1 = 
[[ 0  5  1]
 [ 0 -1  6]
 [ 1  0  0]]; sigma_1 = 31

U2 = 
[[ 0  6 -1]
 [ 0  1  5]
 [ 1  0  0]]; sigma_2 = 31

D = 
[[1. 

In [14]:
my_interface.parse_limit(du = 1e-2, S  = 1e-2, sgm1=200, sgm2=200, dd = 1e-2)

In [26]:
for i in range(len(thetas)):
    R = rot([0,0,1], thetas[i])
    hkl1 = get_primitive_hkl(C_lattice = my_interface.conv_lattice_1, P_lattice = my_interface.lattice_1, hkl = hkls[i])
    my_interface.search_fixed(R, exact = True)
    my_interface.compute_bicrystal(hkl1, plane_ortho=True, normal_ortho= True, lim = 50, tol_ortho = 1e-3)
    x_dimension = ceil(70/norm(dot(my_interface.lattice_1,my_interface.bicrystal_U1)[:,0]))
    hkl2 = get_primitive_hkl(C_lattice = my_interface.conv_lattice_1, P_lattice = dot(R, my_interface.conv_lattice_1), hkl = hkls[i])
    my_interface.get_bicrystal(xyz_1 = [x_dimension,1,1], \
                                   xyz_2 = [x_dimension,1,1], \
                               filename = 'co<001>tst_GBs/sigma{0}_({1} {2} {3})_({4} {5} {6})'.\
                               format(sigmas[i], hkl1[0], hkl1[1], hkl1[2], hkl2[0], hkl[1], hkl[2]),filetype='LAMMPS')

Congrates, we found an appx CSL!

U1 = 
[[ 0  8  1]
 [ 0 -1  9]
 [ 1  0  0]]; sigma_1 = 73

U2 = 
[[ 0  9 -1]
 [ 0  1  8]
 [ 1  0  0]]; sigma_2 = 73

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cell 1:
[[-10   0  -8]
 [-17   0   1]
 [  0   1   0]]
cell 2:
[[ -7   0  -9]
 [-17   0  -1]
 [  0   1   0]]
Congrates, we found an appx CSL!

U1 = 
[[ 0  2  3]
 [ 0 -3  5]
 [ 1  0  0]]; sigma_1 = 19

U2 = 
[[ 0  3  2]
 [ 0 -2  5]
 [ 1  0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cell 1:
[[ 3  0  7]
 [ 5  0 -1]
 [ 0  1  0]]
cell 2:
[[2 0 8]
 [5 0 1]
 [0 1 0]]
Congrates, we found an appx CSL!

U1 = 
[[ 0  6  7]
 [ 0 -1  6]
 [ 1  0  0]]; sigma_1 = 43

U2 = 
[[0 7 6]
 [0 1 7]
 [1 0 0]]; sigma_2 = 43

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

cell 1:
[[ -8   0  -6]
 [-13   0   1]
 [  0   1   0]]
cell 2:
[[ -5   0  -7]
 [-13   0  -1]
 [  0   1   0]]
Congrates, we found an appx CSL!

U1 = 
[[ 0  5  1]
 [ 0 -1  6]
 [ 1  0  0]]; sigma_1 = 31

U2 = 
[[ 0  6 -1]
 [ 0  1  5]
 [ 1  0  0]

In [5]:
my_interface.parse_limit(du = 1e-2, S  = 1e-2, sgm1=200, sgm2=200, dd = 1e-2)

#Do searching!
#We already know that there is a CSL by rotation 180 degrees
my_interface.search_fixed(R)

Congrates, we found an appx CSL!

U1 = 
[[ 1  1  3]
 [ 2  0 -1]
 [ 0  1 -2]]; sigma_1 = 11

U2 = 
[[-1 -1  4]
 [ 1 -1  3]
 [ 0  1  2]]; sigma_2 = 11

D = 
[[ 0.99853888 -0.         -0.00110625]
 [-0.          1.         -0.        ]
 [ 0.00192983 -0.          1.00146112]]



'U1', 'U2' are two sets of indices of the CSL in the two crystals' frames,
'D' is the deformation applied to the crystal 2 to form an approximate CSL

As you can see, to form a twinning structure we need to deform the structure provided!

## Convert the miller indices to be expressed in the primitive cell

Now we need to specify the orientation of our interface, which is by giving a miller indices in expressed in the primitive cell.

In [6]:
"""
The interface plane is the [1,-1,2] plane in the conventional cell and now we \
transform it into primitive cell
"""
hkl = get_primitive_hkl(array([1, 1, -2]), my_interface.conv_lattice_1, my_interface.lattice_1)
hkl

array([-2,  1,  2])

## Compute the indices of the two slabs to make bicrystal

Now let's compute the indices of the two slabs forming the interface
If you want a near orthogonal bicrystal, please set 'orthogonal to yes, 
and adjust the lim & tol.

In [7]:
my_interface.compute_bicrystal(hkl, normal_ortho= True, lim = 50, tol_ortho = 1e-3)

cell 1:
[[ 7  1  1]
 [ 0  2  0]
 [-4  0  1]]
cell 2:
[[ 7 -1 -1]
 [ 7  1 -1]
 [ 4  0  1]]


Here we obtained the two sets of indices to build a bicrystal

## Make a bicrystal!

You can adjust the bicrystal by
1. do expansion by set 'xyz' = [dimX, dimY, dimZ]
2. do RBT by 'dzdy' = a translation vector 
(please confine dzdy in the interface plane, 
for RBT in the normal, please use 'dp1' and 'dp2', to make vacuum in the interface use 'dx');
3. introduce vacuum in the interface by 'dx' = the distance spacing the two crystals
4. adjust the termination by 'dp1', 'dp2' = length of shift of the position of 
the termination from the interface into the bulk
5. introduce vacuum to make a surface in the end of the bicrystal by
'vx' = length of the vaccumn

default: xyz = [1,1,1] and others = 0

In [8]:
my_interface.get_bicrystal(xyz_1 = [1,1,1], xyz_2 = [1,1,1], dx = 0)

Good! You have made a 'POSCAR' file of this bicrystal, we also generated two files named 'cell_1.cif' and 'cell_2.cif' providing the structure of the two slabs.

In [26]:
import shutil
try:
    shutil.rmtree('CNID_inputs')
except:
    print('No existing files')
#To sample the CNID, try
my_interface.sample_CNID(grid = [8,8], xyz_1 = [1,1,1], xyz_2 = [1,1,1], dx = 0.5, filetype = 'LAMMPS', filename = 'atoms')

CNID
[[ 1. -1.]
 [ 0. -2.]
 [ 1.  0.]]
making 64 files...
completed


Please check the generated 'POSCAR.x.y' files. 
The CNID here is expressed in the primitive cell's frame.
You can refer to the cartesian coordinates or in the conventional cell's frame

In [9]:
CNID_cartesian = round(my_interface.CNID,8)
CNID_cartesian

array([[-2.25618721,  6.76856163],
       [-3.90783088, -3.90783088],
       [-5.959899  , -0.        ]])

In [10]:
CNID_conv = round(dot(inv(my_interface.conv_lattice_1)\
                              , my_interface.CNID),8)
CNID_conv

array([[-1.,  1.],
       [-1., -1.],
       [-1., -0.]])