# TiO2 surface slab

In [1]:
from interfacemaster.interface_generator import get_surface_slab
from pymatgen.core.structure import Structure
from numpy import ceil

In [2]:
unit_structure = Structure.from_file('cif_files/TiO2_mp-2657_conventional_standard.cif', \
                                     primitive=False, sort=False, merge_tol=0.0)

## The function below generates a slab with its bc-plane is a specified (hkl) lattice plane
### Customerization options:  
**replica** --- expand from primitive slab cell, **default: [1,1,1]**  
**inclination_tol** --- required minimum cos value of the angle between the basic crossing vector and the surface, **default: gamma angle > 45 degrees**  
**termi_shift** --- shift the termination of the surface, **default: 0**  
**vacuum_height** --- height of vaccum, **default:  0**  
**plane_normal** --- whether requiring the two vectors in the surface plane to be perpendicular, **default: False**  
**normal_perp** --- whether requiring the crossing vector to be perpendicular to the plane, **default:  False**  
**normal_tol** --- tolerance to judge whether normal/perpendicular, **default: 1e-3**  
**lim** --- control the number of generated vectors to search for the crossing vectors and perpendicular vectors, **default: 20**    
**filename** --- name of the generated atom files, **default:  'POSCAR'**  
**filetype** --- type of the generated atom files (for VASP or LAMMPS), **default: 'VASP'**

In [3]:
#get primitive slab, using default setting
slab_structure = get_surface_slab(unit_structure, hkl = [1,1,0], vacuum_height = 20)

cross vector: 
[[-1]
 [-1]
 [ 0]]
length: 6.580720371810977
plane basis: 
[[ 0 -1]
 [ 0  1]
 [ 1  0]]
length: 2.969203 6.580720371810977


In [4]:
#get orthogonal cell
slab_structure = get_surface_slab(unit_structure, hkl = [1,1,0], vacuum_height = 20, \
                                  plane_normal = True, normal_perp = True)

cross vector: 
[[-1]
 [-1]
 [ 0]]
length: 6.580720371810977
plane basis: 
[[ 0 -1]
 [ 0  1]
 [ 1  0]]
length: 2.969203 6.580720371810977


In [5]:
#expansion to reach a required slab size with length_a > 5, length_b > 10, length_c > 10
da, db, dc = ceil(5/6.580720371810977), ceil(10/2.969203), ceil(10/6.580720371810977)
slab_structure = get_surface_slab(unit_structure, hkl = [1,1,0], replica = [da, db, dc], vacuum_height = 20)

cross vector: 
[[-1]
 [-1]
 [ 0]]
length: 6.580720371810977
plane basis: 
[[ 0 -1]
 [ 0  1]
 [ 1  0]]
length: 2.969203 6.580720371810977


**Try other customerization options :D**