In [1]:
import sys
sys.path.append('../interfacemaster/')

In [2]:
from interfacemaster.cellcalc import get_primitive_hkl, get_pri_vec_inplane, get_normal_index, get_normal_from_MI, rot
from interfacemaster.interface_generator import core, print_near_axis, convert_vector_index
from numpy import array, dot, round, cross, eye, pi
from numpy.linalg import inv, det, norm
from gb_code.csl_generator import print_list

In [3]:
my_interface = core('cif_files/C_mp-990448_conventional_standard.cif',\
                    'cif_files/C_mp-990448_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


# Get the two axis aligned to be collinear, expressed in primitive cell

In [4]:
print_list([1,1,1],100)

Sigma:     1  Theta:   0.00 
Sigma:     3  Theta:  60.00 
Sigma:     7  Theta:  38.21 
Sigma:    13  Theta:  27.80 
Sigma:    19  Theta:  46.83 
Sigma:    21  Theta:  21.79 
Sigma:    31  Theta:  17.90 
Sigma:    37  Theta:  50.57 
Sigma:    39  Theta:  32.20 
Sigma:    43  Theta:  15.18 
Sigma:    49  Theta:  43.57 
Sigma:    57  Theta:  13.17 
Sigma:    61  Theta:  52.66 
Sigma:    67  Theta:  24.43 
Sigma:    73  Theta:  11.64 
Sigma:    79  Theta:  33.99 
Sigma:    91  Theta:  10.42 
Sigma:    93  Theta:  42.10 
Sigma:    97  Theta:  30.59 


In [5]:
hkl_1 = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_1, my_interface.lattice_1)
hkl_2 = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_2, my_interface.lattice_2)

# Searching two_dimensional CSL

In [6]:
R = rot(a=[0,0,1],Theta = 11.64/180 * pi)

In [7]:
my_interface.parse_limit(du = 1e-2, S  = 1e-2, sgm1=100, sgm2=100, dd = 1e-2)

#Do searching!
my_interface.search_one_position_2D(hkl_1, hkl_2, theta_range = 1, dtheta=0.01, pre_dt=True, pre_R = R, exact=True)

Congrates, we found an appx CSL!

U1 = 
[[ 8  9]
 [-1  8]
 [ 0  0]]; sigma_1 = 73

U2 = 
[[9 8]
 [1 9]
 [0 0]]; sigma_2 = 73

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

axis = [ 3.23108364e-16  5.59640103e-16 -5.27676003e+00] ; theta = 0.0



# Get bicrystal

In [8]:
my_interface.compute_bicrystal_two_D(hkl_1 = hkl_1, hkl_2=hkl_2, normal_ortho = False, plane_ortho = False, lim = 50, tol_integer = 1e-3)

cell 1:
[[ 0  8  9]
 [ 0 -1  8]
 [ 1  0  0]]
cell 2:
[[0 9 8]
 [0 1 9]
 [1 0 0]]


In [9]:
my_interface.get_bicrystal(two_D = True, xyz_1 = [1,1,1], xyz_2 = [1,1,1], dp1 = 8, filetype= 'VASP')

Please check the POSCAR file