# Twisted Graphene Bilayers

In [21]:
import sys
sys.path.append('../interfacemaster/')

In [22]:
from interfacemaster.cellcalc import get_primitive_hkl, get_pri_vec_inplane, get_normal_index, get_normal_from_MI, rot
from interfacemaster.interface_generator import core, convert_vector_index
from interfacemaster.symmetric_tilt import get_csl_twisted_graphenes
from numpy import array, dot, round, cross, eye, pi, ceil, column_stack, arange
from numpy.linalg import inv, det, norm
from gb_code.csl_generator import print_list
import pandas as pd

In [23]:
#sigmas, rotation angles, CNID areas, num of atoms
sigmas, thetas, A_cnid, anum = get_csl_twisted_graphenes(lim = 10, filename = \
                                                         'cif_files/C_mp-990448_conventional_standard.cif',\
                                                        maxsigma = 100)

21.786789298261727
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[-1  3  0]
 [ 2  1  0]
 [ 0  0 -1]]; sigma_1 = 7

U2 = 
[[-2  3  0]
 [ 1  2  0]
 [ 0  0 -1]]; sigma_2 = 7

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

13.173551107258712
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  2  3]
 [ 0 -3  5]
 [ 1  0  0]]; sigma_1 = 19

U2 = 
[[ 0  3  2]
 [ 0 -2  5]
 [ 1  0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

9.430007907896234
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0 -7 -4]
 [ 0 -3 -7]
 [ 1  0  0]]; sigma_1 = 37

U2 = 
[[ 0 -7 -3]
 [ 0 -4 -7]
 [ 1  0  0]]; sigma_2 = 37

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

7.340993016630101
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  4  5]
 [ 0 -5  9]
 [ 1  0  0]]; sig

Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[  0   8  21]
 [  0 -13   8]
 [  1   0   0]]; sigma_1 = 337

U2 = 
[[ 0 13 21]
 [ 0 -8 13]
 [ 1  0  0]]; sigma_2 = 337

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

14.307676374717687
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[  0 -23 -14]
 [  0  -9 -23]
 [  1   0   0]]; sigma_1 = 403

U2 = 
[[  0 -23  -9]
 [  0 -14 -23]
 [  1   0   0]]; sigma_2 = 403

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

46.82644889274104
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  2 -5]
 [ 0  5 -3]
 [ 1  0  0]]; sigma_1 = 19

U2 = 
[[ 0 -2 -3]
 [ 0  3 -5]
 [ 1  0  0]]; sigma_2 = 19

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

24.432697679454535
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0  7  2]
 [ 0 -2  9]
 [

56.10976183099238
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[  0   8 -17]
 [  0  17  -9]
 [  1   0   0]]; sigma_1 = 217

U2 = 
[[  0  -8  -9]
 [  0   9 -17]
 [  1   0   0]]; sigma_2 = 217

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

56.51899391053306
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0 10  9]
 [ 0 -9 19]
 [ 1  0  0]]; sigma_1 = 271

U2 = 
[[ 0 19 -9]
 [ 0  9 10]
 [ 1  0  0]]; sigma_2 = 271

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

56.85034257361046
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[  0  10 -21]
 [  0  21 -11]
 [  1   0   0]]; sigma_1 = 331

U2 = 
[[  0 -10 -11]
 [  0  11 -21]
 [  1   0   0]]; sigma_2 = 331

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

27.795772496027922
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 =

Congrates, we found an appx CSL!

U1 = 
[[ 0 10  3]
 [ 0 -3 13]
 [ 1  0  0]]; sigma_1 = 139

U2 = 
[[ 0 13 -3]
 [ 0  3 10]
 [ 1  0  0]]; sigma_2 = 139

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

29.84172416468434
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[  0 -11 -15]
 [  0   4 -11]
 [  1   0   0]]; sigma_1 = 181

U2 = 
[[  0 -15 -11]
 [  0  -4 -15]
 [  1   0   0]]; sigma_2 = 181

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

33.25434838376643
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0 12 17]
 [ 0 -5 12]
 [ 1  0  0]]; sigma_1 = 229

U2 = 
[[ 0 17 12]
 [ 0  5 17]
 [ 1  0  0]]; sigma_2 = 229

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

35.983397771357616
Warning!, this programme will rewrite the POSCAR file in this dir!
Congrates, we found an appx CSL!

U1 = 
[[ 0 13  6]
 [ 0 -6 19]
 [ 1  0  0]]; sigma_1 = 283

U2 = 
[[ 0 19 -6]
 [ 0  6 13]
 [ 1  0  0]]; sigm

In [24]:
df = pd.DataFrame(column_stack((sigmas, thetas/pi*180, A_cnid, anum)), index = arange(len(sigmas))+1, \
                  columns = ['sigma','thetas','CNID area','atom number'])
df['sigma'] = df['sigma'].astype('int')
df['atom number'] = df['atom number'].astype('int')
df

sigma     thetas  CNID area  atom number
1       7  21.786789   0.753823           28
2      13  32.204228   0.405905           52
3      19  13.173551   0.277724           76
4      31  17.896551   0.170218          124
5      37   9.430008   0.142615          148
6      43  15.178179   0.122715          172
7      49  16.426421   0.107689          196
8      61   7.340993   0.086504          244
9      67  35.567302   0.078758          268
10     73  11.635051   0.072284          292
11     79  26.007824   0.066794          316
12     91   6.008983   0.057986          364
13     97  29.409311   0.054400          388

In [25]:
my_interface = core('cif_files/C_mp-990448_conventional_standard.cif',\
                    'cif_files/C_mp-990448_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


## Searching two_dimensional CSL

In [26]:
#a known target disorientation giving CSL
R = rot(a=[0,0,1],Theta = 21.786789/180 * pi)

In [27]:
my_interface.parse_limit(du = 1e-3, S  = 1e-3, sgm1=100, sgm2=100, dd = 1e-3)

#Do searching!
my_interface.search_fixed(R=R, exact=True)

Congrates, we found an appx CSL!

U1 = 
[[-1  3  0]
 [ 2  1  0]
 [ 0  0 -1]]; sigma_1 = 7

U2 = 
[[-2  3  0]
 [ 1  2  0]
 [ 0  0 -1]]; sigma_2 = 7

D = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## Get bicrystal

In [28]:
hkl = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_1, my_interface.lattice_1)
my_interface.compute_bicrystal(hkl = hkl, normal_ortho = False, plane_ortho = False, lim = 50, tol_ortho = 1e-2, tol_integer=1e-3)

cell 1:
[[ 0 -1  2]
 [ 0  2  3]
 [-1  0  0]]
cell 2:
[[ 0 -2  1]
 [ 0  1  3]
 [-1  0  0]]


In [29]:
layer_displacement = 3.4
my_interface.get_bicrystal(xyz_1 = [1,1,1], xyz_2 = [1,1,1], \
                           dp1 = 9.99905800e+00 - layer_displacement, filetype= 'VASP')

# Sample CNID 

In [30]:
gridsize = 0.3
n1 = int(ceil(norm(my_interface.CNID[:,0])/gridsize))
n2 = int(ceil(norm(my_interface.CNID[:,1])/gridsize))

In [38]:
import shutil
try:
    shutil.rmtree('CNID_inputs')
except:
    print('No existing files')
my_interface.sample_CNID([n1,n2], dp1 = 9.99905800e+00 - layer_displacement)

CNID
[[ 0.42857143 -0.28571429]
 [ 0.14285714 -0.42857143]
 [ 0.          0.        ]]
making 16 files...
completed


Please check the POSCAR file