In [1]:
import sys
sys.path.append('../interfacemaster/')

In [2]:
from interfacemaster.cellcalc import get_primitive_hkl, get_pri_vec_inplane, get_normal_index, get_normal_from_MI
from interfacemaster.interface_generator import core, print_near_axis, convert_vector_index
from numpy import array, dot, round, cross, eye
from numpy.linalg import inv, det, norm

In [3]:
#https://aip.scitation.org/doi/full/10.1063/1.3489687

In [4]:
my_interface = core('cif_files/C_mp-990448_conventional_standard.cif',\
                    'cif_files/C_mp-990448_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


# Get the two axis aligned to be collinear, expressed in primitive cell

Here, we want the (1,-1,0,2) plane of the Al2O3 coincident whith (1,1,-2,0) plane of ZnO.

Firstly, the programme rotate lattice 2 so that the two lattice plane overlap.

As the normal of the plane have different indices with the miller indices, we need to compute it.

In [5]:
hkl_1 = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_1, my_interface.lattice_1)
hkl_2 = get_primitive_hkl([0, 0, 1], my_interface.conv_lattice_2, my_interface.lattice_2)

# Searching two_dimensional CSL

In [7]:
my_interface.parse_limit(du = 1e-5, S  = 1e-5, sgm1=50, sgm2=50, dd = 1e-5)

#Do searching!
my_interface.search_one_position_2D(hkl_1, hkl_2, theta_range = 180, \
                                    dtheta = 0.01, start = 1)

Congrates, we found an appx CSL!

U1 = 
[[7 3]
 [4 7]
 [0 0]]; sigma_1 = 37

U2 = 
[[7 4]
 [3 7]
 [0 0]]; sigma_2 = 37

D = 
[[ 1.0e+00  1.4e-07  0.0e+00]
 [-1.4e-07  1.0e+00 -0.0e+00]
 [-0.0e+00  0.0e+00  1.0e+00]]

axis = [ 0.        0.       -9.999058] ; theta = 9.43



# Get bicrystal

In [9]:
my_interface.compute_bicrystal_two_D(hkl_1 = hkl_1, hkl_2=hkl_2, normal_ortho = False, plane_ortho = False, lim = 50, tol_integer = 1e-3)

cell 1:
[[0 7 3]
 [0 4 7]
 [1 0 0]]
cell 2:
[[0 7 4]
 [0 3 7]
 [1 0 0]]


In [10]:
my_interface.get_bicrystal(two_D = True, xyz_1 = [1,1,1], xyz_2 = [1,1,1], dp1 = 8, filetype= 'LAMMPS')

Please check the POSCAR file