# Al2O3/ZnO

In [2]:
from interfacemaster.cellcalc import get_primitive_hkl
from interfacemaster.interface_generator import core, convert_vector_index, get_disorientation
from numpy import array, dot, round, cross, eye
from numpy.linalg import inv, det, norm

https://aip.scitation.org/doi/full/10.1063/1.3489687

In [3]:
my_interface = core('cif_files/Al2O3_mp-1143_conventional_standard.cif',\
                    'cif_files/ZnO_mp-2133_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


In [4]:
R = get_disorientation(L1 = my_interface.conv_lattice_1, L2 = my_interface.conv_lattice_2, \
                       v1 = [-1,1,1], hkl1 = [1, -1, 2], \
                       v2 = [0,0,1], hkl2 = [1, 1, 0])
R

array([[-0.0673919 ,  0.8832738 , -0.46398893],
       [-0.96109127,  0.0673919 ,  0.26788413],
       [ 0.26788413,  0.46398893,  0.84436507]])

## Get combining two specified surfaces

Here, we want the (1,-1,0,2) plane of the Al2O3 coincident whith (1,1,-2,0) plane of ZnO.  
Get the miller indices of these two planes expressed in the primitive lattices.

In [5]:
hkl_1 = get_primitive_hkl([1, -1, 2], my_interface.conv_lattice_1, my_interface.lattice_1)
hkl_2 = get_primitive_hkl([1, 1, 0], my_interface.conv_lattice_2, my_interface.lattice_2)

## Searching two_dimensional CSL
To searching for 2D CSL, we use search_one_position_2D() function

In [5]:
my_interface.parse_limit(du = 1e-1, S  = 1e-1, sgm1=100, sgm2=100, dd = 1e-1)

#Do searching!
my_interface.search_one_position_2D(hkl_1, hkl_2, theta_range = 2, \
                                    dtheta = 0.01, pre_R = R, match_tol = 0.01, pre_dt= True)

Congrates, we found an appx CSL!

U1 = 
[[ 0 -5]
 [-1  0]
 [ 1  0]]; sigma_1 = 7

U2 = 
[[0 4]
 [0 8]
 [1 0]]; sigma_2 = 9

D = 
[[ 1.00834944  0.02653473  0.00951351]
 [ 0.02653473  1.03898911 -0.00549263]
 [ 0.00951351 -0.00549263  0.98268735]]

axis = [-18.19345118  10.50399394 -13.33003186] ; theta = 0.0



## Get bicrystal

In [7]:
my_interface.compute_bicrystal_two_D(hkl_1 = hkl_1, hkl_2=hkl_2, normal_ortho = False, lim = 50, tol_ortho = 1e-2, tol_integer=1e-3)

cell 1:
[[ 0  0 -5]
 [-1 -1  0]
 [ 0  1  0]]
cell 2:
[[-1  0  4]
 [ 0  0  8]
 [ 0  1  0]]


In [8]:
my_interface.get_bicrystal(two_D = True, xyz_1 = [1,1,1], xyz_2 = [1,1,1])

Please check the POSCAR file