In [134]:
from cellcalc import get_primitive_hkl
from interface_generator import core, print_near_axis, convert_vector_index
from numpy import array, dot, round
from numpy.linalg import inv

In [120]:
my_interface = core('Te_mp-567313_conventional_standard.cif',\
                    'Te_mp-567313_conventional_standard.cif')

Warning!, this programme will rewrite the POSCAR file in this dir!


/Users/jasonxie/.local/lib/python3.8/site-packages/pymatgen/io/cif.py:1121: UserWarning: Issues encountered while parsing CIF: Some fractional co-ordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))


In [123]:
axis = [1,1,0]

In [129]:
my_interface.parse_limit(du = 1e-4, S  = 1e-4, sgm1=100, sgm2=100, dd = 1e-4)

#Do searching!
#We already know that there is a CSL by rotation 180 degrees
my_interface.search_one_position(axis,73,5,0.01,two_D = True)

[-4.50673972e+00  0.00000000e+00 -2.75958219e-16]
Congrates, we found an appx CSL!

U1 = 
[[ 1  0 12]
 [ 1  0 -7]
 [ 0  1  0]]; sigma_1 = 19

U2 = 
[[-1  0 12]
 [ 1  0  7]
 [ 0  1  0]]; sigma_2 = 19

D = 
[[ 1.00000000e+00 -0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00004227e+00  3.17000000e-05]
 [-0.00000000e+00 -5.47600000e-05  9.99957730e-01]]

axis = [-4.50673972e+00  0.00000000e+00 -2.75958219e-16] ; theta = 74.74



In [132]:
my_interface.compute_bicrystal_two_D(orthogonal = False, lim = 50, tol = 1e-2)

In [133]:
my_interface.get_bicrystal(two_D= True, xyz = [3,1,1])